name: Tests

on:
  push:
    branches: "*"
  pull_request:
    branches: master
  workflow_dispatch:

env:
  PYTEST_ADDOPTS: "--color=yes"

jobs:
  test:
    name: ðŸ““ Build Tutorial Notebook
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: "3.9"
        include:
         - nb-path: "xarray_zarr/cmip6-recipe.ipynb"
         - nb-path: "xarray_zarr/netcdf_zarr_sequential.ipynb"
    steps:
      - uses: actions/checkout@v2
      - name: ðŸ” Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64
      - name: ðŸ” Setup Miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          miniforge-variant: Mambaforge
          miniforge-version: latest
          activate-environment: pangeo-forge-recipes
          use-mamba: true
      - name: ðŸŽ¯ Set cache number
        id: cache-number
        # cache will last 3 days by default
        run: echo CACHE_NUMBER=`expr $(date +'%d%m') / 3` >> $GITHUB_ENV
      - name: ðŸŽ¯ Set environment file
        id: env-file
        run: echo "env_file=ci/py${{ matrix.python-version }}.yml" >> $GITHUB_ENV
      - name: âœ… Check environment variables
        id: check-env
        run: |
          echo "env.CACHE_NUMBER: ${{ env.CACHE_NUMBER }}"
          echo "env.env_file: ${{ env.env_file }}"
      - uses: actions/cache@v2
        name: ðŸ—ƒ Cache environment
        with:
          path: /usr/share/miniconda3/envs/pangeo-forge-recipes
          key: ${{ runner.os }}-conda-${{ matrix.python-version }}-${{ hashFiles( env.env_file ) }}-${{ env.CACHE_NUMBER }}
        id: conda-cache
      - name: ðŸ« Update environment
        run: mamba env update -n pangeo-forge-recipes -f ${{ env.env_file }}
        if: steps.conda-cache.outputs.cache-hit != 'true'
      - name: ðŸ List conda env
        shell: bash -l {0}
        run: |
          conda info
          conda list
      - name: ðŸŒˆ Install pangeo-forge-recipes package
        shell: bash -l {0}
        run: |
          python -m pip install --no-deps -e  .

      ### Everything above here is basically the same as main.yaml

      - name: ðŸ— Build Notebook
        shell: bash -l {0}
        run: >
          pytest --timeout=3000 --nbmake docs/tutorials/${{ env.nb-path }}
